version: '3.8'
services:
#  db:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=tvhstats_dev
#    volumes:
#      - db:/var/lib/postgresql/data
  game:
#    depends_on:
#      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: elixir --sname chess --cookie chess -S mix phx.server
    entrypoint: ["./docker/entrypoint.sh"]
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    image: codechallenge/chess
    volumes:
      - .:/app

#volumes:
#  db: