defmodule ChessWeb.PlayingStruct do
    @color_player_1 "white"
    @color_player_2 "black"
    defstruct turn: nil,
              you: %{
                alive_pieces: %{
                  position00: %{position: {0, 0}, piece: nil},
                  position01: %{position: {0, 1}, piece: nil},
                  position02: %{position: {0, 2}, piece: nil},
                  position03: %{position: {0, 3}, piece: nil},
                  position04: %{position: {0, 4}, piece: nil},
                  position05: %{position: {0, 5}, piece: nil},
                  position06: %{position: {0, 6}, piece: nil},
                  position07: %{position: {0, 7}, piece: nil},
                  position10: %{position: {1, 0}, piece: nil},
                  position11: %{position: {1, 1}, piece: nil},
                  position12: %{position: {1, 2}, piece: nil},
                  position13: %{position: {1, 3}, piece: nil},
                  position14: %{position: {1, 4}, piece: nil},
                  position15: %{position: {1, 5}, piece: nil},
                  position16: %{position: {1, 6}, piece: nil},
                  position17: %{position: {1, 7}, piece: nil},
                  position20: %{position: {2, 0}, piece: nil},
                  position21: %{position: {2, 1}, piece: nil},
                  position22: %{position: {2, 2}, piece: nil},
                  position23: %{position: {2, 3}, piece: nil},
                  position24: %{position: {2, 4}, piece: nil},
                  position25: %{position: {2, 5}, piece: nil},
                  position26: %{position: {2, 6}, piece: nil},
                  position27: %{position: {2, 7}, piece: nil},

                  position30: %{position: {3, 0}, piece: nil},
                  position31: %{position: {3, 1}, piece: nil},
                  position32: %{position: {3, 2}, piece: nil},
                  position33: %{position: {3, 3}, piece: nil},
                  position34: %{position: {3, 4}, piece: nil},
                  position35: %{position: {3, 5}, piece: nil},
                  position36: %{position: {3, 6}, piece: nil},
                  position37: %{position: {3, 7}, piece: nil},


                  position40: %{position: {4, 0}, piece: nil},
                  position41: %{position: {4, 1}, piece: nil},
                  position42: %{position: {4, 2}, piece: nil},
                  position43: %{position: {4, 3}, piece: nil},
                  position44: %{position: {4, 4}, piece: nil},
                  position45: %{position: {4, 5}, piece: nil},
                  position46: %{position: {4, 6}, piece: nil},
                  position47: %{position: {4, 7}, piece: nil},

                  position50: %{position: {5, 0}, piece: nil},
                  position51: %{position: {5, 1}, piece: nil},
                  position52: %{position: {5, 2}, piece: nil},
                  position53: %{position: {5, 3}, piece: nil},
                  position54: %{position: {5, 4}, piece: nil},
                  position55: %{position: {5, 5}, piece: nil},
                  position56: %{position: {5, 6}, piece: nil},
                  position57: %{position: {5, 7}, piece: nil},

                  position60: %{position: {6, 0}, piece: %{type: "pawn", color: @color_player_1}},
                  position61: %{position: {6, 1}, piece: %{type: "pawn", color: @color_player_1}},
                  position62: %{position: {6, 2}, piece: %{type: "pawn", color: @color_player_1}},
                  position63: %{position: {6, 3}, piece: %{type: "pawn", color: @color_player_1}},
                  position64: %{position: {6, 4}, piece: %{type: "pawn", color: @color_player_1}},
                  position65: %{position: {6, 5}, piece: %{type: "pawn", color: @color_player_1}},
                  position66: %{position: {6, 6}, piece: %{type: "pawn", color: @color_player_1}},
                  position67: %{position: {6, 7}, piece: %{type: "pawn", color: @color_player_1}},

                  position70: %{position: {7, 0}, piece: %{type: "rook", color: @color_player_1}},
                  position71: %{position: {7, 1}, piece: %{type: "knight", color: @color_player_1}},
                  position72: %{position: {7, 2}, piece: %{type: "bishop", color: @color_player_1}},
                  position73: %{position: {7, 3}, piece: %{type: "queen", color: @color_player_1}},
                  position74: %{position: {7, 4}, piece: %{type: "king", color: @color_player_1}},
                  position75: %{position: {7, 5}, piece: %{type: "bishop", color: @color_player_1}},
                  position76: %{position: {7, 6}, piece: %{type: "knight", color: @color_player_1}},
                  position77: %{position: {7, 7}, piece: %{type: "rook", color: @color_player_1}},
              }},
              enemy: %{
                alive_pieces: %{
                  position00: %{position: {0, 0}, piece: %{type: "rook", color: @color_player_1}},
                  position01: %{position: {0, 1}, piece: %{type: "knight", color: @color_player_1}},
                  position02: %{position: {0, 2}, piece: %{type: "bishop", color: @color_player_1}},
                  position03: %{position: {0, 3}, piece: %{type: "queen", color: @color_player_1}},
                  position04: %{position: {0, 4}, piece: %{type: "king", color: @color_player_1}},
                  position05: %{position: {0, 5}, piece: %{type: "bishop", color: @color_player_1}},
                  position06: %{position: {0, 6}, piece: %{type: "knight", color: @color_player_1}},
                  position07: %{position: {0, 7}, piece: %{type: "rook", color: @color_player_1}},

                  position10: %{position: {1, 0}, piece: %{type: "pawn", color: @color_player_2}},
                  position11: %{position: {1, 1}, piece: %{type: "pawn", color: @color_player_2}},
                  position12: %{position: {1, 2}, piece: %{type: "pawn", color: @color_player_2}},
                  position13: %{position: {1, 3}, piece: %{type: "pawn", color: @color_player_2}},
                  position14: %{position: {1, 4}, piece: %{type: "pawn", color: @color_player_2}},
                  position15: %{position: {1, 5}, piece: %{type: "pawn", color: @color_player_2}},
                  position16: %{position: {1, 6}, piece: %{type: "pawn", color: @color_player_2}},
                  position17: %{position: {1, 7}, piece: %{type: "pawn", color: @color_player_2}},

                  position20: %{position: {2, 0}, piece: nil},
                  position21: %{position: {2, 1}, piece: nil},
                  position22: %{position: {2, 2}, piece: nil},
                  position23: %{position: {2, 3}, piece: nil},
                  position24: %{position: {2, 4}, piece: nil},
                  position25: %{position: {2, 5}, piece: nil},
                  position26: %{position: {2, 6}, piece: nil},
                  position27: %{position: {2, 7}, piece: nil},

                  position30: %{position: {3, 0}, piece: nil},
                  position31: %{position: {3, 1}, piece: nil},
                  position32: %{position: {3, 2}, piece: nil},
                  position33: %{position: {3, 3}, piece: nil},
                  position34: %{position: {3, 4}, piece: nil},
                  position35: %{position: {3, 5}, piece: nil},
                  position36: %{position: {3, 6}, piece: nil},
                  position37: %{position: {3, 7}, piece: nil},


                  position40: %{position: {4, 0}, piece: nil},
                  position41: %{position: {4, 1}, piece: nil},
                  position42: %{position: {4, 2}, piece: nil},
                  position43: %{position: {4, 3}, piece: nil},
                  position44: %{position: {4, 4}, piece: nil},
                  position45: %{position: {4, 5}, piece: nil},
                  position46: %{position: {4, 6}, piece: nil},
                  position47: %{position: {4, 7}, piece: nil},

                  position50: %{position: {5, 0}, piece: nil},
                  position51: %{position: {5, 1}, piece: nil},
                  position52: %{position: {5, 2}, piece: nil},
                  position53: %{position: {5, 3}, piece: nil},
                  position54: %{position: {5, 4}, piece: nil},
                  position55: %{position: {5, 5}, piece: nil},
                  position56: %{position: {5, 6}, piece: nil},
                  position57: %{position: {5, 7}, piece: nil},

                  position60: %{position: {6, 0}, piece: nil},
                  position61: %{position: {6, 1}, piece: nil},
                  position62: %{position: {6, 2}, piece: nil},
                  position63: %{position: {6, 3}, piece: nil},
                  position64: %{position: {6, 4}, piece: nil},
                  position65: %{position: {6, 5}, piece: nil},
                  position66: %{position: {6, 6}, piece: nil},
                  position67: %{position: {6, 7}, piece: nil},

                  position70: %{position: {7, 0}, piece: nil},
                  position71: %{position: {7, 1}, piece: nil},
                  position72: %{position: {7, 2}, piece: nil},
                  position73: %{position: {7, 3}, piece: nil},
                  position74: %{position: {7, 4}, piece: nil},
                  position75: %{position: {7, 5}, piece: nil},
                  position76: %{position: {7, 6}, piece: nil},
                  position77: %{position: {7, 7}, piece: nil},
                }}
            end

  defmodule ChessWeb.SettingStruct do
    defstruct ready: false,
              cell_selected: nil,
              piece_selected: nil
  end

  defmodule ChessWeb.PiecesStruct do
    defstruct id: nil,
              type: nil,
              position: nil,
              color: nil
  end
